import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { RecordingMetadata } from '@/types/recording'
import { SEVERITY_LABELS } from '@/types/nvh'

export async function generateReport(recording: RecordingMetadata): Promise<Blob> {
  const a = recording.analysisResult
  if (!a) throw new Error('No analysis result')

  const doc = new jsPDF('p', 'mm', 'a4')
  const pageW = doc.internal.pageSize.getWidth()
  let y = 15

  doc.setFontSize(18)
  doc.setTextColor(30, 64, 175)
  doc.text('NVH Road Noise Analysis Report', pageW / 2, y, { align: 'center' })
  y += 8

  doc.setFontSize(10)
  doc.setTextColor(100)
  doc.text('NVH Road Noise Analyzer', pageW / 2, y, { align: 'center' })
  y += 12

  doc.setDrawColor(200)
  doc.line(15, y, pageW - 15, y)
  y += 8

  doc.setFontSize(11)
  doc.setTextColor(50)

  const meta = [
    ['Date', new Date(recording.createdAt).toLocaleString('ko-KR')],
    ['Duration', `${Math.floor(recording.duration / 60)}m ${Math.floor(recording.duration % 60)}s`],
    ['Vehicle', recording.vehicleModel || '-'],
    ['Tire', recording.tireSpec || '-'],
    ['Speed', recording.speed ? `${recording.speed} km/h` : '-'],
    ['Road Surface', recording.roadSurface || '-'],
  ]

  meta.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold')
    doc.text(`${label}:`, 20, y)
    doc.setFont('helvetica', 'normal')
    doc.text(value, 55, y)
    y += 6
  })

  y += 5
  doc.setDrawColor(200)
  doc.line(15, y, pageW - 15, y)
  y += 10

  doc.setFontSize(14)
  doc.setTextColor(30, 64, 175)
  doc.text('1. Overall Noise Level', 15, y)
  y += 10

  doc.setFontSize(11)
  doc.setTextColor(50)
  const levels = [
    ['Overall SPL (A-weighted)', `${a.overallSPL_A.toFixed(1)} dB(A)`],
    ['Peak SPL', `${a.peakSPL.toFixed(1)} dB`],
    ['Leq (Equivalent)', `${a.leqSPL.toFixed(1)} dB(A)`],
  ]

  levels.forEach(([label, value]) => {
    doc.setFont('helvetica', 'normal')
    doc.text(label, 20, y)
    doc.setFont('helvetica', 'bold')
    doc.text(value, 120, y)
    y += 7
  })

  y += 8
  doc.setFontSize(14)
  doc.setTextColor(30, 64, 175)
  doc.text('2. 1/3 Octave Band Analysis', 15, y)
  y += 8

  if (a.octaveBands.length > 0) {
    const canvas = document.createElement('canvas')
    canvas.width = 700
    canvas.height = 250
    const ctx = canvas.getContext('2d')
    if (ctx) {
      drawOctaveBandChart(ctx, canvas, a.octaveBands)
      const imgData = canvas.toDataURL('image/png')
      doc.addImage(imgData, 'PNG', 15, y, pageW - 30, 60)
      y += 65
    }
  }

  y += 5
  doc.setFontSize(14)
  doc.setTextColor(30, 64, 175)
  doc.text('3. NVH Noise Classification', 15, y)
  y += 8

  autoTable(doc, {
    startY: y,
    head: [['Category', 'Level dB(A)', 'Peak Freq (Hz)', 'Severity']],
    body: a.categories.map((c) => [
      c.label,
      c.level_dBA.toFixed(1),
      c.dominantFrequency.toFixed(0),
      SEVERITY_LABELS[c.severity],
    ]),
    theme: 'grid',
    headStyles: { fillColor: [30, 64, 175], fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    margin: { left: 15, right: 15 },
  })

  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10

  if (y > 240) {
    doc.addPage()
    y = 20
  }

  doc.setFontSize(14)
  doc.setTextColor(30, 64, 175)
  doc.text('4. Remarks', 15, y)
  y += 8

  doc.setFontSize(10)
  doc.setTextColor(70)

  const significantCategories = a.categories.filter((c) => c.severity !== 'low')
  if (significantCategories.length > 0) {
    significantCategories.forEach((c) => {
      const text = `- ${c.label}: Detected at ${c.dominantFrequency.toFixed(0)}Hz, ` +
        `level ${c.level_dBA.toFixed(1)} dB(A), severity: ${SEVERITY_LABELS[c.severity]}`
      doc.text(text, 20, y, { maxWidth: pageW - 40 })
      y += 6
    })
  } else {
    doc.text('- Overall noise levels are within acceptable range.', 20, y)
    y += 6
  }

  if (recording.notes) {
    y += 3
    doc.text(`Notes: ${recording.notes}`, 20, y, { maxWidth: pageW - 40 })
  }

  const pageH = doc.internal.pageSize.getHeight()
  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text('Generated by NVH Road Noise Analyzer PWA', pageW / 2, pageH - 10, {
    align: 'center',
  })

  return doc.output('blob')
}

function drawOctaveBandChart(
  ctx: CanvasRenderingContext2D,
  canvas: HTMLCanvasElement,
  bands: { centerFrequency: number; level_dBA: number }[],
) {
  const w = canvas.width
  const h = canvas.height
  const pad = { top: 20, right: 20, bottom: 40, left: 50 }
  const chartW = w - pad.left - pad.right
  const chartH = h - pad.top - pad.bottom
  const minDb = -80
  const maxDb = -10
  const range = maxDb - minDb

  ctx.fillStyle = '#ffffff'
  ctx.fillRect(0, 0, w, h)

  ctx.strokeStyle = '#e2e8f0'
  ctx.lineWidth = 1
  ctx.fillStyle = '#64748b'
  ctx.font = '11px sans-serif'
  ctx.textAlign = 'right'

  for (let db = minDb; db <= maxDb; db += 10) {
    const y = pad.top + chartH * (1 - (db - minDb) / range)
    ctx.beginPath()
    ctx.moveTo(pad.left, y)
    ctx.lineTo(w - pad.right, y)
    ctx.stroke()
    ctx.fillText(`${db}`, pad.left - 5, y + 4)
  }

  const barW = Math.max(4, (chartW / bands.length) * 0.7)
  const gap = chartW / bands.length

  bands.forEach((band, i) => {
    const x = pad.left + i * gap + (gap - barW) / 2
    const normalizedH = Math.max(0, (band.level_dBA - minDb) / range) * chartH
    const y = pad.top + chartH - normalizedH

    ctx.fillStyle = '#3b82f6'
    ctx.fillRect(x, y, barW, normalizedH)

    if (i % 3 === 0) {
      ctx.save()
      ctx.translate(x + barW / 2, h - pad.bottom + 10)
      ctx.rotate(-Math.PI / 4)
      ctx.fillStyle = '#64748b'
      ctx.font = '9px sans-serif'
      ctx.textAlign = 'right'
      const f = band.centerFrequency
      const label = f >= 1000 ? `${(f / 1000).toFixed(f >= 10000 ? 0 : 1)}k` : `${f}`
      ctx.fillText(label, 0, 0)
      ctx.restore()
    }
  })
}
